In [3]:
import pandas as pd
import numpy as np

In [5]:
from pycaret.regression import *

In [7]:
import mlflow

In [4]:
data = pd.read_csv("raw.csv")
data.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner

In [8]:
mlflow.set_tracking_uri('http://127.0.0.1:5000')

In [9]:
s = setup(data, 
          target='Rent', 
          session_id=123, 
          experiment_name='modelo_base', 
          log_experiment=True)

2023/06/24 12:57:37 INFO mlflow.tracking.fluent: Experiment with name 'modelo_base' does not exist. Creating a new experiment.

In [10]:
best = compare_models()

In [ ]:
model1 = create_model('rf')

In [11]:
tune = tune_model(best, n_iter = 100)

Fitting 10 folds for each of 100 candidates, totalling 1000 fits

In [12]:
final = finalize_model(tune)

In [13]:
get_logs()

RestException: RESOURCE_DOES_NOT_EXIST: Could not find experiment with ID None